name: Generate Contribution Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      # 1. Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Generate contribution snake
      - name: Generate snake SVGs
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: sumaiya143
          outputs: |
            profile/github-contribution-grid-snake.svg
            profile/github-contribution-grid-snake-dark.svg?palette=github-dark

      # 3. Save generated SVGs to the repository
      - name: Commit generated files
        uses: EndBug/add-and-commit@v9
        with:
          message: "chore: update contribution snake"
          add: "profile/*.svg"
